- hosts: remote
  remote_user: ec2-user
  gather_facts: False
  tasks:
    # - name: create testbed dirs
    #   file:
    #     path: /home/ec2-user/testbed/PlainDAG/PlainDAG{{item}}/testbed
    #     state: directory
    #   loop: [0, 1]
    #   loop_control:
    #     loop_var: item
    #   ignore_errors: yes

    - name: run PlainDAG as a daemon
      shell: "(nohup ./go-PlainDAG> /home/ec2-user/testbed/PlainDAG/PlainDAG{{item}}/testbed/{{inventory_hostname}}_{{item}}.txt 2>&1 &)"
      args:
        chdir: /home/ec2-user/testbed/PlainDAG/PlainDAG{{item}}
      loop: [0]
      loop_control:
        loop_var: item
      ignore_errors: yes
